apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-events-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-events-processor
  template:
    metadata:
      labels:
        app: todo-events-processor
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: todo-app  # Używamy istniejącego Service Account
      containers:
      - name: todo-events-processor
        image: tododockerregistry.azurecr.io/todo-app/todo-events-processor:latest
        env:
        - name: KeyVaultName
          value: "kv-todo-app"
        - name: StorageAccountName
          value: "todoappstaccteam2"