apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-events-processor
spec:
  selector:
    matchLabels:
      app: todo-events-processor
  template:
    metadata:
      labels:
        app: todo-events-processor
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: todo-app  # Używamy istniejącego Service Account
      containers:
      - name: todo-events-processor
        image: tododockerregistry.azurecr.io/todo-app/todo-events-processor:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: KeyVaultName
          value: "kv-todo-app"
        - name: StorageAccountName
          value: "todoappstaccteam2"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: servicebus-trigger-auth
spec:
  secretTargetRef:
  - parameter: connection
    name: servicebus-secret  # Nazwa secretu
    key: connection          # Klucz w secrecie
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: todo-worker-scaler
spec:
  scaleTargetRef:
    name: todo-events-processor
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 5
  cooldownPeriod: 30
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: todoevents
      messageCount: "5"
    authenticationRef:
      name: servicebus-trigger-auth  # Odwołanie do TriggerAuthentication