apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: todo-app
  template:
    metadata:
      labels:
        name: todo-app
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: todo-app
      containers:
      - name: todo-counter
        image: tododockerregistry.azurecr.io/todo-app/todo-image:${TAG}
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=tcp:lab-sql-02.database.windows.net,1433;Initial Catalog=lab-02-sql;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=Active Directory Default;"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=53a1b502-8dfd-4183-b1a3-28602e0a8c73;IngestionEndpoint=https://polandcentral-0.in.applicationinsights.azure.com/;LiveEndpoint=https://polandcentral.livediagnostics.monitor.azure.com/;ApplicationId=a3619664-f7d8-4206-8cb4-21f445efed3c"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-app
  annotations:
    azure.workload.identity/client-id: "2c57becb-1733-464a-879f-350d67f9652a"
