name: build_deploy_todo_aks
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.AZURE_CLIENT_ID }}
          service_principal_password: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant: ${{ secrets.AZURE_TENANT_ID }}
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          repository: todo-app
          image:  todo-image
          folder: src/ToDo
          branch: main
          tag: ${{ github.sha }}
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'RG-lab02' 
          cluster-name: 'todo-aks-lab2'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v4
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v5
        with:
          namespace: 'default'
          manifests: |
             src/ToDo/Deployment/deployment.yaml
             src/ToDo/Deployment/service.yaml
             src/ToDo/Deployment/ingress.yaml
          images: '${{ secrets.ACR_LOGIN_SERVER }}.azurecr.io/todo-app/todo-image:${{ github.sha }}'
          pull-images: false 